### ISSUE TITLE
Add docker file

### ISSUE THREAD

**Issue by Anurag5086** [Code-dig-ger/Frontend#13]
Add a docker file to create an image of this repository. Refer [this](https://docs.docker.com/engine/reference/builder/).

**Comment by poohcom1** [comment]
Hello! I'm interested in contributing on this issue, so I would like to ask for some details.

Are you guys planning on using the docker image for development or production, or both? 
If it's for development, live-reload won't be available, so I'm thinking about using a docker-compose file to automate the processing of mounting volumes; is that something you guys are looking for?

Cheers

**Comment by Anurag5086** [comment]
@poohcom1 Thanks for showing your interest, we want the docker image for development as well as production. Sure, we can go ahead by creating docker-compose file.

**Comment by Anurag5086** [comment]
Hey @poohcom1 , are you working on this issue?

**Comment by poohcom1** [comment]
> 
> 
> Hey @poohcom1 , are you working on this issue?

Yep, I was doing some final tests to make sure it works on both Windows and Linux. I'm about to raise the PR

**Comment by Anurag5086** [comment]
Great! 💯
