### ISSUE TITLE
Login Screen

### ISSUE THREAD

**Issue by Sheetal575** [Code-dig-ger/Frontend#38]
**Is your feature request related to a problem? Please describe.**
Login form is so small according to the screen size. it seems like lot of space is unused which makes a bad impact on user

**Describe the solution you'd like**
we can increase it size by giving more padding and also make input boxes color according to the theme of website.

![image](https://user-images.githubusercontent.com/56470040/145550292-6ea3f291-3dc1-4884-ab9c-2ba0e0196d69.png)

**Comment by Sheetal575** [comment]
i did it please assign me to make a pull request.
@Anurag5086

**Comment by LegendSumeet** [comment]
@Sheetal575  you've been assigned!  go aheadd..

**Comment by saikeshari** [comment]
Hi @Sheetal575 , We are revamping our design, so you can post the work done on this page here - https://github.com/Code-dig-ger/Frontend/discussions/17.

**Comment by Sheetal575** [comment]
@saikeshari  okay

**Comment by Sheetal575** [comment]
Why did you closed it
