### ISSUE TITLE
Review and Edit Contributing Guidelines (CONTRIBUTING.md File )

### ISSUE THREAD

**Issue by ShivamSinghal1** [Code-dig-ger/Frontend#9]
A CONTRIBUTING file tells our audience how to participate in your project. 
For example, you might include information on:

- How to file a bug report (try using issue and pull request templates)
- How to suggest a new feature
- How to set up your environment and run tests

In addition to technical details, a CONTRIBUTING file is an opportunity to communicate your expectations for contributions, such as:

- The types of contributions you’re looking for
- Your roadmap or vision for the project
- How contributors should (or should not) get in touch with you

Using a warm, friendly tone and offering specific suggestions for contributions (such as writing documentation, or making a website) can go a long way in making newcomers feel welcomed and excited to participate.

In the earliest stages of your project, your CONTRIBUTING file can be simple. You should always explain how to report bugs or file issues, and any technical requirements (like tests) to make a contribution.

[Template Contributing File ](https://github.com/nayafia/contributing-template/blob/HEAD/CONTRIBUTING-template.md)
More about - 

- [1](https://mozillascience.github.io/working-open-workshop/contributing/)
- [2](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)

[Example](https://github.com/activeadmin/activeadmin/blob/HEAD/CONTRIBUTING.md)

**Comment by Anurag5086** [comment]
@ShivamSinghal1 File looks good. I'm close this issue.
